import type { PrimaryCSP } from "./types";

export const mockCSPs: PrimaryCSP[] = [
  {
    id: "csp-1",
    companyName: "GlobalCorp Services Ltd",
    contactName: "John Smith",
    email: "john@globalcorp.com",
    phone: "+65 1234 5678",
    jurisdiction: "Singapore",
    status: "active",
    kybStatus: "verified",
    subscriptionTier: "enterprise",
    monthlyRevenue: 15000,
    activeClients: 45,
    joinDate: "2024-01-15",
  },
  {
    id: "csp-2",
    companyName: "Asia Business Hub Pte",
    contactName: "Sarah Chen",
    email: "sarah@asiahub.com",
    phone: "+65 9876 5432",
    jurisdiction: "Singapore",
    status: "active",
    kybStatus: "verified",
    subscriptionTier: "professional",
    monthlyRevenue: 8500,
    activeClients: 28,
    joinDate: "2024-02-20",
  },
  {
    id: "csp-3",
    companyName: "Offshore Solutions Inc",
    contactName: "Michael Brown",
    email: "michael@offshore.com",
    phone: "+1 555 0123",
    jurisdiction: "BVI",
    status: "pending",
    kybStatus: "pending",
    subscriptionTier: "starter",
    monthlyRevenue: 0,
    activeClients: 0,
    joinDate: "2024-03-10",
  },
  {
    id: "csp-4",
    companyName: "European Trust Partners",
    contactName: "Emma Wilson",
    email: "emma@europetrust.com",
    phone: "+44 20 1234 5678",
    jurisdiction: "UK",
    status: "active",
    kybStatus: "verified",
    subscriptionTier: "professional",
    monthlyRevenue: 12000,
    activeClients: 35,
    joinDate: "2024-01-05",
  },
  {
    id: "csp-5",
    companyName: "Pacific Rim Advisors",
    contactName: "David Lee",
    email: "david@pacificrim.com",
    phone: "+852 1234 5678",
    jurisdiction: "Hong Kong",
    status: "suspended",
    kybStatus: "rejected",
    subscriptionTier: "starter",
    monthlyRevenue: 0,
    activeClients: 12,
    joinDate: "2024-02-01",
  },
];