type InvoiceStatus = "paid" | "pending" | "overdue" | "failed";
type InvoiceType = "primary_csp" | "partner" | "promoted_listing";

export interface Invoice {
  id: string;
  invoiceNumber: string;
  date: string;
  customerId: string;
  customerName: string;
  customerType: InvoiceType;
  amount: number;
  status: InvoiceStatus;
  dueDate: string;
  paidDate?: string;
  description: string;
}

export const mockInvoices: Invoice[] = [
  {
    id: "inv_001",
    invoiceNumber: "INV-2024-0421",
    date: "15 May 24",
    customerId: "001",
    customerName: "London CSP",
    customerType: "primary_csp",
    amount: 1000,
    status: "paid",
    dueDate: "15 May 24",
    paidDate: "15 May 24",
    description: "Pro Plan - May 2024",
  },
  {
    id: "inv_002",
    invoiceNumber: "INV-2024-0422",
    date: "15 May 24",
    customerId: "001",
    customerName: "Singapore CSP",
    customerType: "partner",
    amount: 50,
    status: "paid",
    dueDate: "15 May 24",
    paidDate: "15 May 24",
    description: "Basic Plan - May 2024",
  },
  {
    id: "inv_003",
    invoiceNumber: "INV-2024-0423",
    date: "15 May 24",
    customerId: "001",
    customerName: "BVI Trust Services",
    customerType: "promoted_listing",
    amount: 200,
    status: "paid",
    dueDate: "15 May 24",
    paidDate: "15 May 24",
    description: "Promoted Listing - BVI",
  },
  {
    id: "inv_004",
    invoiceNumber: "INV-2024-0398",
    date: "01 May 24",
    customerId: "002",
    customerName: "New York Law",
    customerType: "primary_csp",
    amount: 300,
    status: "paid",
    dueDate: "01 May 24",
    paidDate: "01 May 24",
    description: "Starter Plan - May 2024",
  },
  {
    id: "inv_005",
    invoiceNumber: "INV-2024-0399",
    date: "01 May 24",
    customerId: "004",
    customerName: "Malta CSP",
    customerType: "partner",
    amount: 50,
    status: "overdue",
    dueDate: "01 May 24",
    description: "Basic Plan - May 2024",
  },
  {
    id: "inv_006",
    invoiceNumber: "INV-2024-0424",
    date: "20 May 24",
    customerId: "003",
    customerName: "Hong Kong Trust",
    customerType: "primary_csp",
    amount: 3000,
    status: "paid",
    dueDate: "20 May 24",
    paidDate: "20 May 24",
    description: "Enterprise Plan - May 2024",
  },
  {
    id: "inv_007",
    invoiceNumber: "INV-2024-0425",
    date: "22 May 24",
    customerId: "005",
    customerName: "Dubai Partners",
    customerType: "primary_csp",
    amount: 3000,
    status: "pending",
    dueDate: "22 May 24",
    description: "Enterprise Plan - May 2024",
  },
  {
    id: "inv_008",
    invoiceNumber: "INV-2024-0426",
    date: "22 May 24",
    customerId: "003",
    customerName: "Cayman Fund Services",
    customerType: "promoted_listing",
    amount: 200,
    status: "paid",
    dueDate: "22 May 24",
    paidDate: "22 May 24",
    description: "Promoted Listing - Cayman Islands",
  },
  {
    id: "inv_009",
    invoiceNumber: "INV-2024-0400",
    date: "10 May 24",
    customerId: "004",
    customerName: "Singapore Firm",
    customerType: "primary_csp",
    amount: 1000,
    status: "overdue",
    dueDate: "10 May 24",
    description: "Pro Plan - May 2024",
  },
  {
    id: "inv_010",
    invoiceNumber: "INV-2024-0427",
    date: "25 May 24",
    customerId: "005",
    customerName: "Luxembourg Trust",
    customerType: "partner",
    amount: 100,
    status: "paid",
    dueDate: "25 May 24",
    paidDate: "25 May 24",
    description: "Premium Plan - May 2024",
  },
  {
    id: "inv_011",
    invoiceNumber: "INV-2024-0428",
    date: "01 Jun 24",
    customerId: "009",
    customerName: "Test Primary CSP",
    customerType: "primary_csp",
    amount: 300,
    status: "pending",
    dueDate: "01 Jun 24",
    description: "Starter Plan - June 2024",
  },
  {
    id: "inv_012",
    invoiceNumber: "INV-2024-0401",
    date: "08 May 24",
    customerId: "008",
    customerName: "Cayman Corp",
    customerType: "primary_csp",
    amount: 1000,
    status: "failed",
    dueDate: "08 May 24",
    description: "Pro Plan - May 2024",
  },
];