import type { Payment } from "./types";

export const mockPayments: Payment[] = [
  {
    id: "pay-1",
    customerName: "Global Legal Services Ltd",
    customerType: "provider",
    amount: 2499,
    currency: "USD",
    status: "completed",
    method: "card",
    date: "2024-03-01",
    invoiceId: "INV-2024-001",
    description: "Enterprise Plan - Monthly Subscription",
  },
  {
    id: "pay-2",
    customerName: "Smith & Associates",
    customerType: "partner",
    amount: 499,
    currency: "USD",
    status: "completed",
    method: "bank_transfer",
    date: "2024-03-01",
    invoiceId: "INV-2024-002",
    description: "Professional Plan - Monthly Subscription",
  },
  {
    id: "pay-3",
    customerName: "International Tax Advisors",
    customerType: "provider",
    amount: 999,
    currency: "USD",
    status: "pending",
    method: "card",
    date: "2024-03-02",
    invoiceId: "INV-2024-003",
    description: "Professional Plan - Monthly Subscription",
  },
  {
    id: "pay-4",
    customerName: "Cross Border Experts",
    customerType: "partner",
    amount: 299,
    currency: "USD",
    status: "failed",
    method: "paypal",
    date: "2024-03-02",
    invoiceId: "INV-2024-004",
    description: "Starter Plan - Monthly Subscription",
  },
  {
    id: "pay-5",
    customerName: "Euro Compliance Group",
    customerType: "provider",
    amount: 2499,
    currency: "EUR",
    status: "completed",
    method: "bank_transfer",
    date: "2024-03-03",
    invoiceId: "INV-2024-005",
    description: "Enterprise Plan - Monthly Subscription",
  },
  {
    id: "pay-6",
    customerName: "Asia Pacific Partners",
    customerType: "partner",
    amount: 499,
    currency: "USD",
    status: "completed",
    method: "crypto",
    date: "2024-03-03",
    invoiceId: "INV-2024-006",
    description: "Professional Plan - Monthly Subscription",
  },
  {
    id: "pay-7",
    customerName: "Latin America Services",
    customerType: "provider",
    amount: 999,
    currency: "USD",
    status: "refunded",
    method: "card",
    date: "2024-03-04",
    invoiceId: "INV-2024-007",
    description: "Professional Plan - Monthly Subscription (Refunded)",
  },
  {
    id: "pay-8",
    customerName: "UK Legal Network",
    customerType: "partner",
    amount: 299,
    currency: "GBP",
    status: "completed",
    method: "card",
    date: "2024-03-04",
    invoiceId: "INV-2024-008",
    description: "Starter Plan - Monthly Subscription",
  },
];