type ListingStatus = "active" | "pending" | "expired";

export interface PromotedListing {
  id: string;
  partnerId: string;
  partnerName: string;
  jurisdiction: string;
  status: ListingStatus;
  startDate: string;
  endDate: string;
  amount: number;
  renewsOn: string;
  category: string;
}

export const mockListings: PromotedListing[] = [
  {
    id: "pl_001",
    partnerId: "001",
    partnerName: "Singapore CSP",
    jurisdiction: "Singapore",
    status: "active",
    startDate: "20 May 24",
    endDate: "20 Jun 24",
    amount: 200,
    renewsOn: "20 Jun 24",
    category: "Company Formation",
  },
  {
    id: "pl_002",
    partnerId: "002",
    partnerName: "BVI Trust Services",
    jurisdiction: "BVI",
    status: "active",
    startDate: "22 May 24",
    endDate: "22 Jun 24",
    amount: 200,
    renewsOn: "22 Jun 24",
    category: "Trust Services",
  },
  {
    id: "pl_003",
    partnerId: "003",
    partnerName: "Cayman Fund Services",
    jurisdiction: "Cayman Islands",
    status: "active",
    startDate: "25 May 24",
    endDate: "25 Jun 24",
    amount: 200,
    renewsOn: "25 Jun 24",
    category: "Fund Services",
  },
  {
    id: "pl_004",
    partnerId: "004",
    partnerName: "Malta CSP",
    jurisdiction: "Malta",
    status: "pending",
    startDate: "01 Jun 24",
    endDate: "01 Jul 24",
    amount: 200,
    renewsOn: "01 Jul 24",
    category: "Accounting",
  },
  {
    id: "pl_005",
    partnerId: "005",
    partnerName: "Luxembourg Trust",
    jurisdiction: "Luxembourg",
    status: "active",
    startDate: "18 May 24",
    endDate: "18 Jun 24",
    amount: 200,
    renewsOn: "18 Jun 24",
    category: "Banking",
  },
  {
    id: "pl_006",
    partnerId: "006",
    partnerName: "Seychelles Corp",
    jurisdiction: "Seychelles",
    status: "expired",
    startDate: "10 Apr 24",
    endDate: "10 May 24",
    amount: 200,
    renewsOn: "N/A",
    category: "Legal Services",
  },
  {
    id: "pl_007",
    partnerId: "007",
    partnerName: "Mauritius Services",
    jurisdiction: "Mauritius",
    status: "active",
    startDate: "28 May 24",
    endDate: "28 Jun 24",
    amount: 200,
    renewsOn: "28 Jun 24",
    category: "Company Formation",
  },
  {
    id: "pl_008",
    partnerId: "008",
    partnerName: "Dubai Partners",
    jurisdiction: "UAE",
    status: "active",
    startDate: "05 Jun 24",
    endDate: "05 Jul 24",
    amount: 200,
    renewsOn: "05 Jul 24",
    category: "Real Estate",
  },
  {
    id: "pl_009",
    partnerId: "009",
    partnerName: "Gibraltar Legal",
    jurisdiction: "Gibraltar",
    status: "pending",
    startDate: "03 Jun 24",
    endDate: "03 Jul 24",
    amount: 200,
    renewsOn: "03 Jul 24",
    category: "Legal Services",
  },
  {
    id: "pl_010",
    partnerId: "010",
    partnerName: "Cyprus Trust Co",
    jurisdiction: "Cyprus",
    status: "active",
    startDate: "15 May 24",
    endDate: "15 Jun 24",
    amount: 200,
    renewsOn: "15 Jun 24",
    category: "Trust Services",
  },
  {
    id: "pl_011",
    partnerId: "011",
    partnerName: "Panama Services",
    jurisdiction: "Panama",
    status: "expired",
    startDate: "05 Apr 24",
    endDate: "05 May 24",
    amount: 200,
    renewsOn: "N/A",
    category: "Company Formation",
  },
  {
    id: "pl_012",
    partnerId: "012",
    partnerName: "Hong Kong CSP",
    jurisdiction: "Hong Kong",
    status: "active",
    startDate: "12 May 24",
    endDate: "12 Jun 24",
    amount: 200,
    renewsOn: "12 Jun 24",
    category: "Banking",
  },
  {
    id: "pl_013",
    partnerId: "013",
    partnerName: "Labuan Partners",
    jurisdiction: "Malaysia",
    status: "active",
    startDate: "08 May 24",
    endDate: "08 Jun 24",
    amount: 200,
    renewsOn: "08 Jun 24",
    category: "Company Formation",
  },
  {
    id: "pl_014",
    partnerId: "014",
    partnerName: "Isle of Man Trust",
    jurisdiction: "Isle of Man",
    status: "pending",
    startDate: "02 Jun 24",
    endDate: "02 Jul 24",
    amount: 200,
    renewsOn: "02 Jul 24",
    category: "Trust Services",
  },
  {
    id: "pl_015",
    partnerId: "015",
    partnerName: "Bahamas Fund",
    jurisdiction: "Bahamas",
    status: "active",
    startDate: "30 May 24",
    endDate: "30 Jun 24",
    amount: 200,
    renewsOn: "30 Jun 24",
    category: "Fund Services",
  },
];