import type { Client } from "./types";

export const mockClients: Client[] = [
  {
    id: "c1",
    name: "John Smith",
    email: "john@techcorp.com",
    company: "Tech Corp Ltd",
    status: "active",
    activeEngagements: 3,
    totalSpent: 12500,
    joinDate: "2023-09-15",
    lastActivity: "2024-03-05",
  },
  {
    id: "c2",
    name: "Sarah Johnson",
    email: "sarah@globalventures.com",
    company: "Global Ventures Inc",
    status: "active",
    activeEngagements: 2,
    totalSpent: 8900,
    joinDate: "2023-11-20",
    lastActivity: "2024-03-06",
  },
  {
    id: "c3",
    name: "Michael Chen",
    email: "m.chen@innovations.com",
    company: "Innovations LLC",
    status: "pending",
    activeEngagements: 1,
    totalSpent: 3500,
    joinDate: "2024-02-10",
    lastActivity: "2024-03-04",
  },
  {
    id: "c4",
    name: "Emily Rodriguez",
    email: "emily@startupco.com",
    company: "StartUp Co",
    status: "inactive",
    activeEngagements: 0,
    totalSpent: 5200,
    joinDate: "2023-06-08",
    lastActivity: "2024-01-15",
  },
  {
    id: "c5",
    name: "David Kim",
    email: "david@enterprise.com",
    company: "Enterprise Solutions",
    status: "active",
    activeEngagements: 4,
    totalSpent: 18700,
    joinDate: "2023-08-22",
    lastActivity: "2024-03-07",
  },
];